/*
 * @(#)Local.java
 *
 * Copyright (c) 2002 Nokia Mobile Phones. All Rights Reserved.
 */

//WARNING: If there exists a number in the MIDLet-abbreviation or package name 
//         there could appear errors in the following line!
package com.nokia.mid.appl.cmd;

import br.org.indt.ndg.mobile.settings.LanguageHandler;
import java.io.*;

/**
* The Local class constructor sets the localisation language. The localisation language is the
* language into which the internationalised texts, i.e. text ids are replaced by
* the concrete strings in the target language.
* <br>
* The localisation language is normally the phone language which is selected by the user
* provided that this language will also be supported by the MIDlet. In case that the phone
* language is not supported by the MIDlet, all texts are localised in <b>english</b>.
* <p>
* Additionally, the Local class provides the methods for the localisation, i.e. the translation of
* logical text ids to the localised strings. This includes also the replacement of formal parameters
* in the localised texts by the concrete values.
* <p>
* @author 	Dieter H?ner, Ralf Engels, Mathias Gaupp
* @version	0.6 28-Oct-2004 Local.java is now generated by Nokia-I18N-Tool.
* @version	0.5 16-Feb-2003 Small improvements concerning mark and reset.
* @version	0.4 27-Aug-2003 Support mark and reset.
* @version	0.3 05-Aug-2002 Local.java is now generated by MIDlet_dat2lan.
* @version	0.2 02-Aug-2002 Improvement for localization.
* @version	0.1 30-Apr-2002 Initial version
*/
public class Local {


    /**
     * Class object representing the Local object.
     * Only used for internal help when an object reference is needed.
     */
    private static Local loc = null;

    /** Data input stream used for reading texts.
     *  Only DataInputStreams supporting mark are stored.
     */
    private static DataInputStream dis = null;

    public final static short QTJ_CMD_BACK = 0;
    public final static short QTJ_CMD_SEND = 1;
    public final static short QTJ_OPEN_RESULT = 2;
    public final static short QTJ_CMD_DELETE = 3;
    public final static short QTJ_CMD_SAVE = 4;
    public final static short QTJ_CMD_EXIT = 5;
    public final static short QTJ_CMD_NEW_SURVEY = 6;
    public final static short QTJ_CMD_RESULTS = 7;
    public final static short QTJ_CMD_NEXT = 8;
    public final static short QTJ_CMD_START = 9;
    public final static short QTJ_CMD_VIEW = 10;
    public final static short QTJ_CMD_VIEWSENT = 11;
    public final static short QTJ_CMD_MARKALL = 12;
    public final static short QTJ_CMD_UNMARKALL = 13;
    public final static short QTJ_CMD_CANCEL = 14;
    public final static short QTJ_CMD_MOVETOUNSENT = 15;
    public final static short QTJ_CMD_QUESTIONS = 16;
    public final static short QTJ_CMD_RESULTADOS = 17;
    public final static short QTJ_CMD_SURVEYS = 18;
    public final static short QTJ_CMD_OK = 19;
    public final static short QTJ_CMD_SAVE_SETTINGS = 20;
    public final static short QTJ_CMD_SETTINGS = 21;
    public final static short QTJ_CMD_GPSTEST = 22;
    public final static short QTJ_QUESTION_LIST_TITLE = 23;
    public final static short QTJ_RESULTS_LIST_TITLE = 24;
    public final static short QTJ_SUBMIT_LIST_TITLE = 25;
    public final static short QTJ_SENT_LIST_TITLE = 26;
    public final static short QTJ_CATEGORY_LIST_TITLE = 27;
    public final static short QTJ_SETTINGS = 28;
    public final static short QTJ_GPS = 29;
    public final static short QTJ_SERVER = 30;
    public final static short QTJ_DISPLAY = 31;
    public final static short QTJ_SUBMIT_SERVER = 32;
    public final static short QTJ_SUBMIT_FILE = 33;
    public final static short QTJ_YES = 34;
    public final static short QTJ_NO = 35;
    public final static short QTJ_ALWAYS = 36;
    public final static short QTJ_SOMETIMES = 37;
    public final static short QTJ_NEVER = 38;
    public final static short QTJ_MALE = 39;
    public final static short QTJ_FEMALE = 40;
    public final static short QTJ_APPNAME = 41;
    public final static short QTJ_CATEGORY = 42;
    public final static short QTJ_CMD_CATEGORIES = 43;
    public final static short QTJ_SURVEY_LIST_TITLE = 44;
    public final static short QTJ_SAVE_MODIFICATIONS = 45;
    public final static short QTJ_NOT_VISITED = 46;
    public final static short QTJ_MSG_SERVER_CANT_WRITE_RESULTS = 47;
    public final static short QTJ_ELOAD_SURVEY = 48;
    public final static short QTJ_ELOAD_SURVEYS = 49;
    public final static short QTJ_ELOAD_RESULTS = 50;
    public final static short QTJ_EDELETE_RESULT = 51;
    public final static short QTJ_ELEAVE_MIDLET = 52;
    public final static short QTJ_ELOAD_IMAGES = 53;
    public final static short QTJ_ESET_ROOT = 54;
    public final static short QTJ_EPARSE_SAX = 55;
    public final static short QTJ_EPARSE_SURVEY = 56;
    public final static short QTJ_EPARSE_RESULT = 57;
    public final static short QTJ_EPARSE_GENERAL = 58;
    public final static short QTJ_EWRITE_RESULT = 59;
    public final static short QTJ_ECREATE_RESULT = 60;
    public final static short QTJ_ESEND_RESULT1 = 61;
    public final static short QTJ_ESEND_RESULT2 = 62;
    public final static short QTJ_ESEND_RESULT3 = 63;
    public final static short QTJ_ERENAME = 64;
    public final static short QTJ_RANGE = 65;
    public final static short QTJ_ON = 66;
    public final static short QTJ_OFF = 67;
    public final static short QTJ_COMPRESSION = 68;
    public final static short QTJ_GPS_LOCATION = 69;
    public final static short QTJ_FONT = 70;
    public final static short QTJ_RESULTS_LIST_RANGE_TITLE = 71;
    public final static short QTJ_SMALL = 72;
    public final static short QTJ_MEDIUM = 73;
    public final static short QTJ_LARGE = 74;
    public final static short QTJ_MORE_RESULTS = 75;
    public final static short QTJ_LOADING_SURVEY = 76;
    public final static short QTJ_PROCESSING = 77;
    public final static short QTJ_WAIT = 78;
    public final static short QTJ_LOADING_RESULTS = 79;
    public final static short QTJ_SAVING_RESULT = 80;
    public final static short QTJ_CMD_OPEN = 81;
    public final static short QTJ_CMD_DOWNLOAD = 82;
    public final static short QTJ_DOWNLOAD_NEW_SURVEYS = 83;
    public final static short QTJ_CHECK_NEW_SURVEYS = 84;
    public final static short QTJ_CONNECTING = 85;
    public final static short QTJ_DOWNLOADING_NEW_SURVEYS = 86;
    public final static short QTJ_EWEBSERVER_ERROR = 87;
    public final static short QTJ_EDOWNLOAD_FAILED_ERROR_CODE = 88;
    public final static short QTJ_EDOWNLOAD_FAILED_HTTP_CODE = 89;
    public final static short QTJ_EDOWNLOAD_FAILED_INVALID_MIME_TYPE = 90;
    public final static short QTJ_EDOWNLOAD_FAILED_INVALID_DATA = 91;
    public final static short QTJ_EDOWNLOAD_INCOMPLETED = 92;
    public final static short QTJ_EDOWNLOAD_ACK_ERROR = 93;
    public final static short QTJ_EINVALID_SURVEYS = 94;
    public final static short QTJ_EINVALID_XML_FILE = 95;
    public final static short QTJ_CMD_DELETE_SURVEY = 96;
    public final static short QTJ_DELETE_CONFIRMATION = 97;
    public final static short QTJ_DELETE_RESULTS_CONFIRMATION = 98;
    public final static short QTJ_DELETE_SURVEY_CONFIRMATION = 99;
    public final static short QTJ_NO_RESULTS_SELECTED = 100;
    public final static short QTJ_SELECT_RESULTS_DELETE = 101;
    public final static short QTJ_IMPOSSIBLE_CREATE_ROOTDIR = 102;
    public final static short QTJ_NO_SURVEYS = 103;
    public final static short QTJ_THERE_ARE_NO_SURVEYS = 104;
    public final static short QTJ_ERROR_TITLE = 105;
    public final static short QTJ_GPS_LOCAL = 106;
    public final static short QTJ_CONNECTED = 107;
    public final static short QTJ_LATITUDE = 108;
    public final static short QTJ_LONGITUDE = 109;
    public final static short QTJ_ALTITUDE = 110;
    public final static short QTJ_HORIZONTAL_ACCU = 111;
    public final static short QTJ_VERTICAL_ACCU = 112;
    public final static short QTJ_NETWORK_FAILURE = 113;
    public final static short QTJ_TRY_AGAIN_LATER = 114;
    public final static short QTJ_INTEGER = 115;
    public final static short QTJ_VALUE_GREATER = 116;
    public final static short QTJ_VALUE_LOWER = 117;
    public final static short QTJ_NO_DETAILS = 118;
    public final static short QTJ_NO_DETAILS_ALTERNATIVE = 119;
    public final static short QTJ_NO_TRANSPORT = 120;
    public final static short QTJ_NO_TRANSPORT_SELECTED = 121;
    public final static short QTJ_SURVEY_NOT_IN_SERVER = 122;
    public final static short QTJ_MORE_DETAILS = 123;
    public final static short QTJ_EINVALID_SURVEY = 124;
    public final static short QTJ_DELETE_RESULT_CONFIRMATION = 125;
    public final static short QTJ_QUESTION = 126;
    public final static short QTJ_QUESTIONS = 127;
    public final static short QTJ_END_OF_SURVEY = 128;
    public final static short QTJ_PRESS_OK_TO_SAVE = 129;
    public final static short QTJ_CHECK_FOR_UPDATE = 130;
    public final static short QTJ_WARNING = 131;
    public final static short QTJ_NEW_SURVEY_RECEIVED = 132;
    public final static short QTJ_CMD_VIEW_GPS_DETAILS = 133;
    public final static short QTJ_AGREEMENT_TEXT = 134;
    public final static short QTJ_CMD_ACCEPT = 135;
    public final static short QTJ_CMD_DECLINE = 136;
    public final static short QTJ_SURVEY_NOT_DOWNLOADED = 137;
    public final static short QTJ_CMD_TEST_CONNECTION = 138;
    public final static short QTJ_TESTING_CONNECTION = 139;
    public final static short QTJ_CONNECTION_OK = 140;
    public final static short QTJ_CONNECTION_FAILED = 141;
    public final static short QTJ_GPRS_LABEL = 142;
    public final static short QTJ_SMS_LABEL = 143;
    public final static short QTJ_CMD_HIDE = 144;
    public final static short QTJ_CONNECTION_WAIT_FOR_ACK = 145;
    public final static short QTJ_CMD_SELECT = 146;
    public final static short QTJ_CMD_OPTIONS = 147;
    public final static short QTJ_CHECK_FOR_UPDATE_TITLE = 148;
    public final static short QTJ_NDG_UPDATED = 149;
    public final static short QTJ_NDG_NOT_UPDATED = 150;
    public final static short QTJ_DECIMAL = 151;
    public final static short QTJ_DATE = 152;
    public final static short QTJ_NEW_INTERVIEW = 153;
    public final static short QTJ_EDITING = 154;
    public final static short QTJ_TRY_AGAIN = 155;
    public final static short QTJ_REGISTERING_APP = 156;
    public final static short QTJ_REGISTRATION_DONE = 157;
    public final static short QTJ_APP_REGISTERED = 158;
    public final static short QTJ_APP_REGISTRATION_FAILED = 159;
    public final static short QTJ_NDG_CHECK_NTWRK = 160;
    public final static short QTJ_NDG_NO_ROUTE = 161;
    public final static short QTJ_NDG_SOFTWARE_ABORT = 162;
    public final static short QTJ_NDG_CONNECTION_REFUSED = 163;
    public final static short QTJ_NDG_PERMISSION_DENIED = 164;
    public final static short QTJ_NDG_NETWORK_DOWN = 165;
    public final static short QTJ_NDG_NETWORK_UNREACHABLE = 166;
    public final static short QTJ_NDG_CONNECTION_TIMEOUT = 167;
    public final static short QTJ_NDG_NETWORK_UNAVAILABLE = 168;
    public final static short QTJ_NDG_HOST_NOT_FOUND = 169;
    public final static short QTJ_HTTP_NOT_FOUND = 170;
    public final static short QTJ_HTTP_FORBIDDEN = 171;
    public final static short QTJ_HTTP_BAD_REQUEST = 172;
    public final static short QTJ_HTTP_UNAUTHORIZED = 173;
    public final static short QTJ_HTTP_INTERNAL_ERROR = 174;
    public final static short QTJ_HTTP_OVERLOADED = 175;
    public final static short QTJ_CHECK_SERVER = 176;
    public final static short QTJ_FAILED = 177;
    public final static short QTJ_NDG_NO_DNS = 178;
    public final static short QTJ_NDG_NO_LOCATION = 179;
    public final static short QTJ_NDG_DEVICE_NOT_READY = 180;
    public final static short QTJ_IMEI_ALREADY_EXISTS = 181;
    public final static short QTJ_MSISDN_NOT_FOUND = 182;
    public final static short QTJ_REGISTRATION_FAILURE = 183;
    public final static short QTJ_SUCCESS = 184;
    public final static short QTJ_MSISDN_ALREADY_REGISTERED = 185;
    public final static short QTJ_WIRELESS_INTERFACE_ERROR = 186;
    public final static short QTJ_THERE_ARE_NO_NEW_SURVEYS = 187;
    public final static short QTJ_CATEGORYVIEW_CONFIGURATION = 188;
    public final static short QTJ_CATEGORYVIEW = 189;
    public final static short QTJ_NOTPROPERINTEGER = 190;
    public final static short QTJ_NOTPROPRDECIMAL = 191;
    public final static short QTJ_RESTORE_DEFAULT = 192;
    public final static short QTJ_RELOAD = 193;
    public final static short QTJ_UI_SETTINGS = 194;
    public final static short QTJ_APPLY = 195;
    public final static short QTJ_LOADING_STYLE = 196;
    public final static short QTJ_LOADING_STYLE_ERROR = 197;
    public final static short QTJ_UI_CUSTOMIZE = 198;
    public final static short QTJ_SELECTED = 199;
    public final static short QTJ_UNSELECTED = 200;
    public final static short QTJ_PREVIEW = 201;
    public final static short QTJ_ELEMENT = 202;
    public final static short QTJ_OBJECT = 203;
    public final static short QTJ_LIST = 204;
    public final static short QTJ_MENU = 205;
    public final static short QTJ_DIALOG_TITLE = 206;
    public final static short QTJ_BG_SELECTED = 207;
    public final static short QTJ_BG_UNSELECTED = 208;
    public final static short QTJ_FONT_SELECTED = 209;
    public final static short QTJ_FONT_UNSELECTED = 210;
    public final static short QTJ_ACCESS_DENIED = 211;
    public final static short QTJ_LOAD_FROM_FILE = 212;
    public final static short QTJ_MEMORY_OUT = 213;
    public final static short QTJ_DEFAULT_PHOTO_DIR = 214;
    public final static short QTJ_CAPTURE_PHOTO = 215;
    public final static short QTJ_DELETE_PHOTO = 216;
    public final static short QTJ_PHOTO_RESOLUTION = 217;
    public final static short QTJ_SHOW_PHOTO = 218;
    public final static short QTJ_TAKE_PHOTO = 219;
    public final static short QTJ_JUST_SAVE = 220;
    public final static short QTJ_UI_PREFERENCES = 221;
    public final static short QTJ_GEO_TAGGING_CONF = 222;
    public final static short QTJ_MAX_IMG_NO = 223;
    public final static short QTJ_RESOLUTIONS = 224;
    public final static short QTJ_DEFAULT = 225;
    public final static short QTJ_HIGH_CONTRAST = 226;
    public final static short QTJ_CUSTOM = 227;
    public final static short QTJ_STYLES = 228;
    public final static short QTJ_TIME_FORMAT_ERROR = 229;
    public final static short QTJ_DATE_FORMAT_ERROR = 230;
    public final static short QTJ_DISCARD_CHANGES = 231;
    public final static short QTJ_APPLICATION_SETTINGS = 232;
    public final static short QTJ_PROTOCOL_SETTINGS = 233;

    public final static short QTJ_ENCRYPTION = 234;
    public final static short QTJ_ENCRYPTION_ENABLE = 235;
    public final static short QTJ_ENCRYPTION_WITH_PASSWORD = 236;
    public final static short QTJ_ENCRYPTION_PASSWORD = 237;
    public final static short QTJ_DECRYPTION_FAILED = 238;
    public final static short QTJ_DECOMPRESSION_FAILED = 239;
    public final static short QTJ_DECRYPTION_DISABLED = 240;
    public final static short QTJ_EMPTY_KEY = 241;
    public final static short QTJ_WRONG_KEY = 242;


    public static String phoneLang = System.getProperty("microedition.locale");


    /**
     * Generates a Local object.
     * Only for internal use.
     */
    private Local() {
      ; // do nothing
    }
    
    static {
        LanguageHandler handler = new LanguageHandler();
        phoneLang = handler.getLanguage();
    }


    /**
     * The method replaces a substring by another one.
     * @param source  source string in which the replacement will take place
     * @param replace substring to be replaced
     * @param by      replacing substring
     */
    public static String replace( String source, String replace, String by ) {

        int place;

        do {
            // begin of substring to be replaced
            place = source.indexOf(replace);

            // return new string after replacement
            if( place >= 0 )
                source = source.substring(0, place) + by + source.substring(place+replace.length());
        } while( place >=0 );

        return source;
    }


    /**
     * The method translates the logical text id to the localized string.     * @param ltid         logical text id (internationalised form) of text that has to be localised
     */
    public static synchronized String getText(int ltid) {
        return getText( ltid, null );
    }



    /**
     * The method translates the logical text id to the localised string.
     * This includes also the replacement of formal parameters in the localized
     * text by the concrete value.
     * @param ltid         logical text id (internationalised form) of text that has to be localized
     * @param p                Array of strings that replace the formal parameters in the localized text
     */
    public static synchronized String getText(int ltid, String p[]) {

        try {

            // create Local object if necessary
            if (loc == null) 
                loc = new Local();

            if( dis == null ) {
                // open resource file depending on the localisation language
                InputStream is = loc.getClass().getResourceAsStream("/resources/text/lang."+phoneLang.substring(0,2));
                if( is == null )
                    is = loc.getClass().getResourceAsStream("/resources/text/lang.en");

                if (is == null)
                    return "X";

                dis = new DataInputStream(is);

                dis.mark( 512 ); // try to mark
            }

            // get the localised text depending on logical text id and the localisation language

            // first get offset
            dis.skipBytes(ltid*2);
            short offset = dis.readShort();

            dis.skipBytes(offset-ltid*2-2);
            String str = dis.readUTF();

            // throw away the data input stream if it does not reset
            if( !dis.markSupported() ) {
                dis.close();
                dis = null;
            } else {
                try {
                    dis.reset();
                } catch(IOException ex) {
                    dis.close();
                    dis = null;
                }
            }

            // replace all formal parameters by correct substrings
            if( p!=null ) {
                if (p.length == 1)
                    str = replace( str, "%U", p[0]);
                else
                    for( int i=0; i<p.length; i++ )
                        str = replace( str, "%"+i+"U", p[i] );
            }

            // return localised text
            return str;

        } catch(IOException ex) {
            dis = null;
            return "E";
        }
    }
}
